### ISSUE TITLE
rosrun sjtu_drone drone_keyboard not working

### ISSUE THREAD

**Issue by aaryapatel007** [tahsinkose/sjtu-drone#1]
got the following error when running `rosrun sjtu_drone drone_keyboard`
```
/home/aarya/catkin_ws/src/sjtu-drone/src/drone_keyboard.cpp: line 6: syntax error near unexpected token `('
/home/aarya/catkin_ws/src/sjtu-drone/src/drone_keyboard.cpp: line 6: `int main(int argc, char** argv){'
```
when compiling `g++ drone_keyboard.cpp -o drone_keyboard -I/opt/ros/melodic/include -L/opt/ros/melodic/lib -lroscpp -lrostime -lrosconsole` I get the following error:
```
In file included from drone_keyboard.cpp:2:0:
DialogKeyboard.h:4:10: fatal error: QDialog: No such file or directory
 #include <QDialog>
          ^~~~~~~~~
compilation terminated.
```

**Comment by tahsinkose** [comment]
This is a problem of QT. Do you have QT5 installed?

**Comment by aaryapatel007** [comment]
NO

**Comment by tahsinkose** [comment]
I think you should install it. By the ways, I didn't touch to any implementation of those teleoperation and other source files. I have just changed the Gazebo plugin to conform it to Gazebo 9.

**Comment by tahsinkose** [comment]
Please inform me when your problem is solved so that I can close the issue.

**Comment by 08beeqtufail-sudo** [comment]
Hello guys,
I was testing the sjtu simulator as part of a company project but i can't make the teleoperation work. @aaryapatel007 , did you manage to get it working ? What environment (ros, linux, gazebo), you were using? 
I am using ROS melodic, ubuntu 18 and gazebo 9. 

@tahsinkose , the CMakeLists.txt file assosciated with your code is different than the original file (older versions). Notably, your version doesn't compile the teleoperation part (drone_keyboard). Hence i had to use that part from the older versions but it doesn't seem to work. 
Or am i missing something here ? 

Thanks for your time guys!

**Comment by tahsinkose** [comment]
Hey @08beeqtufail-sudo 

I never needed to use keyboard application, since I was using `rqt` and automated scripts to test stuff, but since this was asked multiple times I had to spent 2-3 hours fixing it.

With commit https://github.com/tahsinkose/sjtu-drone/commit/a0e732be35ea2f06fcb9b9657a96f8e04a21623b, the keyboard GUI application is now usable. The CMakeLists from the older repo was just broken, therefore I had removed that executable totally.

**Comment by DongXingshuai** [comment]
dongxingshuai@lenovo-legion-y7000-2020h:~$ cd uav/sjtu_drone/catkin_ws/
dongxingshuai@lenovo-legion-y7000-2020h:~/uav/sjtu_drone/catkin_ws$ source devel/setup.bash 
dongxingshuai@lenovo-legion-y7000-2020h:~/uav/sjtu_drone/catkin_ws$ rosrun sjtu_drone drone_keyboard
dongxingshuai@lenovo-legion-y7000-2020h:~/uav/sjtu_drone/catkin_ws$ rosrun sjtu_drone drone_keyboard
key:Z
take off !
[ INFO] [1610705850.077800999]: Taking Off...
key:Z has been released !
[ INFO] [1610705850.216276321]: Hovering...
key:A
[ INFO] [1610705865.301094383]: Rolling...
key:A has been released !
[ INFO] [1610705865.456916359]: Hovering...
key:I
[ INFO] [1610705874.234001989]: Rising...
key:I has been released !
[ INFO] [1610705874.417459221]: Hovering...


Hi tahsinkose, thank you for sharing the code. I am testing the sjtu simulator. Unfortunately, when I run "rosrun sjtu_drone drone_keyboard" and press the corresponding buttons the drone did not move as expected. Please refer to the screenshots (https://drive.google.com/file/d/1oxNhQjU8oVkp7QlszebG3ToPClGAx2HC/view?usp=sharing) (https://drive.google.com/file/d/15jIvbCL82B3tcw76Ga-_aWGu4x4x7Qo5/view?usp=sharing). Can you give me any suggestions? Thank you very much.

**Comment by tahsinkose** [comment]
@DongXingshuai you need to press "Resume" button in Gazebo.

**Comment by DongXingshuai** [comment]
> @DongXingshuai you need to press "Resume" button in Gazebo.

Thank you very much.
