### ISSUE TITLE
#include ui_DialogKeyboard.h doesn't exist

### ISSUE THREAD

**Issue by patrick1bauer** [tahsinkose/sjtu-drone#6]
When running 'catkin build' the following error occurs:

Errors     << sjtu_drone:make /home/patrick/catkin_ws/logs/sjtu_drone/build.make.000.log
/home/patrick/catkin_ws/src/sjtu-drone/src/DialogKeyboard.cpp:1:10: fatal error: ui_DialogKeyboard.h: No such file or directory
 #include "ui_DialogKeyboard.h"
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/drone_keyboard.dir/src/DialogKeyboard.cpp.o] Error 1
make[1]: *** [CMakeFiles/drone_keyboard.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [all] Error 2
cd /home/patrick/catkin_ws/build/sjtu_drone; catkin build --get-env sjtu_drone | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
...............................................................................
Failed     << sjtu_drone:make                      [ Exited with code 2 ]      
Failed    <<< sjtu_drone                           [ 16.2 seconds ]            
[build] Summary: 1 of 2 packages succeeded.                                    
[build]   Ignored:   None.                                                     
[build]   Warnings:  None.                                                     
[build]   Abandoned: None.                                                     
[build]   Failed:    1 packages failed.                                        
[build] Runtime: 17.7 seconds total.                                           
[build] Note: Workspace packages have changed, please re-source setup files to use them.

**Comment by akmandor** [comment]
I am having the same issue with ROS Melodic + Gazebo 9. Any solution?

**Comment by oscarkfpang** [comment]
I managed to solve the problem. I've got the same problem on Ubuntu 18 ROS Melodic and Gazebo 9. In catkin_make in the workspace I got this error message: fatal error: ui_DialogKeyboard.h: No such file or directory
 #include "ui_DialogKeyboard.h"
          ^~~~~~~~~~~~~~~~~~~~~

First make sure you've installed qt by running
sudo apt-get install qt5-default

Then, I realise that in the CMakeList.txt, under part "5. A program using the keyboard to control the quadrotor", there's a line #119
set(CMAKE_AUTOUIC ON)

By googling I find this solution in https://stackoverflow.com/questions/44967065/cmake-qt5-cant-generate-header-file-for-ui-file-autouic

And edit src/DialogKeyboard.cpp , add a blank line above #include "ui_DialogKeyboard.h", save and catkin_make again. Then it manage to compile successfully.

**Comment by tahsinkose** [comment]
Added suggested change by @oscarkfpang with https://github.com/tahsinkose/sjtu-drone/commit/2204df186820269998df28f32c6a52928393b91b. Thanks @patrick1bauer for raising and @oscarkfpang for solving :pray:
