### ISSUE TITLE
Error: package 'meshes' not found

### ISSUE THREAD

**Issue by SimpleMathmatics** [tahsinkose/sjtu-drone#7]
After successfully compiling the package, I get the following error when running the launch file:

[rospack] Error: package 'meshes' not found
[librospack]: error while executing command
[FATAL] [1619970202.332698782, 0.001000000]: Package[meshes] does not have a path
Service call failed: service [/gazebo/spawn_urdf_model] responded with an error: 
[ERROR] [1619970202.333698, 0.001000]: Spawn service failed. Exiting.
[spawn_gazebo_model-4] process has died [pid 3377, exit code 1, cmd /opt/ros/melodic/lib/gazebo_ros/spawn_model -urdf -param robot_description -model sjtu_drone -x 0 -y 0 -z 0 __name:=spawn_gazebo_model __log:=/home/julian/.ros/log/15dfa844-ab5d-11eb-ac87-0800273d4af1/spawn_gazebo_model-4.log].
log file: /home/julian/.ros/log/15dfa844-ab5d-11eb-ac87-0800273d4af1/spawn_gazebo_model-4*.log
[Err] [ModelDatabase.cc:390] Unable to parse model.config for model[http://gazebosim.org/models/bin_4_dropping_task]

Does anybody have a solution to this?

**Comment by tahsinkose** [comment]
Fixed.
